<!DOCTYPE csit [
    <!ELEMENT csit (student+)>
<!ELEMENT student (name+,age,roll,address)>
<!ELEMENT name (fName,lName)>
<!ELEMENT fName (#PCDATA)>
<!ELEMENT lName (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT address (#PCDATA)>
]>

<csit>
    <student>
        <name>
            <fName>Diwash</fName>
            <lName>Pokhrel</lName>
        </name>
        <age>21</age>
        <roll>14</roll>
        <address>Damak</address>
    </student>
    <student>
        <name>
            <fName>Sumit</fName>
            <lName>Shrestha</lName>
        </name>
        <age>21</age>
        <roll>40</roll>
        <address>Gokarna</address>
    </student>
    <student>
        <name>
            <fName>Monu</fName>
            <lName>Siddiki</lName>
        </name>
        <age>21</age>
        <roll>14</roll>
        <address>Surkhet</address>
    </student>
</csit>